/**
 * @file	errmsg.h
 * @brief	Error messages for the AMPL-2020 parser.
 * @author	W.H.K. Bester (whkbester@cs.sun.ac.za)
 * @date	2020-08-12
 */

#ifndef ERRMSG_H
#define ERRMSG_H

typedef enum {
	ERR_EXPECT,
	ERR_ILLEGAL_ARRAY_OPERATION,
	ERR_ILLEGAL_BACK_EXPRESSION,
	ERR_ILLEGAL_INDEXED_ARRAY_ALLOCATION,
	ERR_MISSING_ARRAY_ALLOCATION_OR_EXPRESSION,
	ERR_MISSING_BACK_EXPRESSION,
	ERR_MISSING_FACTOR,
	ERR_MISSING_STATEMENT,
	ERR_MISSING_STRING_OR_EXPRESSION,
	ERR_MISSING_TYPE,
	ERR_MULTIPLE_DEFINITION,
	ERR_NOT_A_FUNCTION,
	ERR_NOT_AN_ARRAY,
	ERR_NOT_A_PROCEDURE,
	ERR_NOT_A_VARIABLE,
	ERR_SCALAR_VARIABLE_EXPECTED,
	ERR_TOO_FEW_ARGUMENTS,
	ERR_TOO_MANY_ARGUMENTS,
	ERR_UNKNOWN_IDENTIFIER,
	ERR_UNREACHABLE
} Error;

#endif /* ERRMSG_H */
